serverAddr = "pcfs.eno.ink"
serverPort = 7000
[[proxies]]
name = "25565"
type = "tcp"
localIP = "127.0.0.1"
localPort = 25565
remotePort = 10011

[auth]
method = "token"
token = "Bloret-PCFS-Token-Now-Rhedar-Detrital"
